import argparse, sys
import tanghulu

version = '1.0'

class HelpMessage():
    epibedPath = "input file, epibed.gz format, generated by biscuit and indexed"
    cpgPath = "genomic CpG file, gz format and Indexed"
    region = "one region, in the format of chr:start-end"
    outputDir = "output directory name"
    tag = "prefix of the output file(s)"
    outFormat = "output format, pdf or png [pdf]"
    outcut = "the max length of region to plot [2000]"

if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    subparsers = parser.add_subparsers()
    help = HelpMessage()

    tanghulu_parser = subparsers.add_parser('tanghulu', help="Show the phased DNA methylation and SNP at fragment-level (In paired-end mode)")
    tanghulu_parser.add_argument('--epibedPath', type=str, required=True, help=help.epibedPath)
    tanghulu_parser.add_argument('--cpgPath', type=str, required=True, help=help.cpgPath)
    tanghulu_parser.add_argument('--region', type=str, required=True, help=help.region)
    tanghulu_parser.add_argument('--outputDir', type=str, required=True, help=help.outputDir)
    tanghulu_parser.add_argument('--tag', type=str, required=True, help=help.tag + " [chr:start_end]")
    tanghulu_parser.add_argument('--outFormat', type=str, required=False, default='pdf', help=help.outFormat)
    tanghulu_parser.add_argument('--outcut', type=int, default=2000, help=help.outcut)
    tanghulu_parser.set_defaults(func='tanghulu')

    args = parser.parse_args()
    try:
        args.func
    except:
        print('EpiReadTk: A comprehensive tool kit for analysis of EpiRead')
        print('version:', version)
        sys.exit()

    if args.func == "tanghulu":
        tanghulu.main(args)
    else:
        print("Unrecognized command: " + args.func)
        sys.exit()