from enum import Enum

class CODE(Enum):
    IGNORE= 0
    UNMETHYLATED = 1
    METHYLATED = 2
    DELETION = -1
    A_REPLACE = 11
    T_REPLACE = 12
    C_REPLACE = 13
    G_REPLACE = 14
    AorG_REPLACE = 15
    CorT_REPLACE = 16
    A_INSERT = 21
    T_INSERT = 22
    C_INSERT = 23
    G_INSERT = 24
    UNKNOWN_INSERT = 25
CODE.IGNORE.label = 'Fx'
CODE.UNMETHYLATED.label = 'U'
CODE.METHYLATED.label = 'M'
CODE.DELETION.label1 = 'D'
CODE.DELETION.label2 = 'd'
CODE.A_REPLACE.label = 'A'
CODE.T_REPLACE.label = 'T'
CODE.C_REPLACE.label = 'C'
CODE.G_REPLACE.label = 'G'
CODE.AorG_REPLACE.label = 'R'
CODE.CorT_REPLACE.label = 'Y'
CODE.A_INSERT.label = 'a'
CODE.T_INSERT.label = 't'
CODE.C_INSERT.label = 'c'
CODE.G_INSERT.label = 'g'
CODE.UNKNOWN_INSERT.label = 'i'

CPG_DICT = {CODE.UNMETHYLATED.label: CODE.UNMETHYLATED.value, CODE.METHYLATED.label: CODE.METHYLATED.value}
SNP_DICT = {CODE.DELETION.label1: CODE.DELETION.value, CODE.DELETION.label2: CODE.DELETION.value,
            CODE.A_REPLACE.label: CODE.A_REPLACE.value, CODE.T_REPLACE.label: CODE.T_REPLACE.value,
            CODE.C_REPLACE.label: CODE.C_REPLACE.value, CODE.G_REPLACE.label: CODE.G_REPLACE.value,
            CODE.AorG_REPLACE.label: CODE.AorG_REPLACE.value, CODE.CorT_REPLACE.label: CODE.CorT_REPLACE.value,
            CODE.A_INSERT.label: CODE.A_INSERT.value, CODE.T_INSERT.label: CODE.T_INSERT.value,
            CODE.C_INSERT.label: CODE.C_INSERT.value, CODE.G_INSERT.label: CODE.G_INSERT.value,
            CODE.UNKNOWN_INSERT.label: CODE.UNKNOWN_INSERT.value}
SNP_DICT_INV = {CODE.DELETION.value: CODE.DELETION.label1,
            CODE.A_REPLACE.value: CODE.A_REPLACE.label, CODE.T_REPLACE.value: CODE.T_REPLACE.label,
            CODE.C_REPLACE.value: CODE.C_REPLACE.label, CODE.G_REPLACE.value: CODE.G_REPLACE.label,
            CODE.AorG_REPLACE.value: CODE.AorG_REPLACE.label, CODE.CorT_REPLACE.value: CODE.CorT_REPLACE.label,
            CODE.A_INSERT.value: CODE.A_INSERT.label, CODE.T_INSERT.value: CODE.T_INSERT.label,
            CODE.C_INSERT.value: CODE.C_INSERT.label, CODE.G_INSERT.value: CODE.G_INSERT.label,
            CODE.UNKNOWN_INSERT.value: CODE.UNKNOWN_INSERT.label}
SNP_REPLACE_ATCG_DICT = {CODE.A_REPLACE.label: CODE.A_REPLACE.value, CODE.T_REPLACE.label: CODE.T_REPLACE.value,
            CODE.C_REPLACE.label: CODE.C_REPLACE.value, CODE.G_REPLACE.label: CODE.G_REPLACE.value}
SNP_REPLACE_RY_DICT = {CODE.AorG_REPLACE.label: CODE.AorG_REPLACE.value, CODE.CorT_REPLACE.label: CODE.CorT_REPLACE.value}
SNP_DETELE_DICT= {CODE.DELETION.label1: CODE.DELETION.value, CODE.DELETION.label2: CODE.DELETION.value}
SNP_INSERT_DICT = {CODE.A_INSERT.label: CODE.A_INSERT.value, CODE.T_INSERT.label: CODE.T_INSERT.value,
            CODE.C_INSERT.label: CODE.C_INSERT.value, CODE.G_INSERT.label: CODE.G_INSERT.value,
            CODE.UNKNOWN_INSERT.label: CODE.UNKNOWN_INSERT.value}